# 6. Norma inducida

##### Importando librerías

In [1]:
import numpy as np
import random

##### Se crea un algoritmo donde lo primero que hace es crear una matriz NxM, luego se crean varios vectores canonicos de tamaño N y de cantidad M. Se multiplican esos vectores Canonicos con la matriz creada y el resultados son otros vectores. A estos vectores se le saca la norma P y luego se escoge el maximo valor de estas normas generadas. El resultado seria la Norma Inducida de la matriz generada.

In [2]:
def random_matrix(n, m):
    # Generate a random matrix of size n by m with integer numbers
    matrix = np.random.randint(low=0, high=10, size=(n, m))
    return matrix

def random_canonical_vectors(n, m):
    # Generate m random canonical vectors of size n
    vectors = []
    for i in range(m):
        e = np.zeros(n)
        e[i % n] = 1
        vectors.append(e)
    return vectors

def minkowski_norm(x, p):
    # Calculate the Minkowski norm of a vector x with order p
    if p == 1:
        norm = np.sum(np.abs(x))
    elif p == 2:
        norm = np.sqrt(np.sum(np.square(x)))
    elif p == float('inf'):
        norm = np.max(np.abs(x))
    return norm

def max_minkowski_norm(n, m, p):
    # Generate a random matrix of size n by m with integer numbers
    x = random_matrix(n, m)
    # Generate m random canonical vectors of size n
    vectors_canonicos = random_canonical_vectors(n, m)
    # Calculate the product of the matrix and the canonical vectors
    resultado = [np.transpose(x) @ vectors_canonicos[i] for i in range(len(vectors_canonicos))]
    # Calculate the Minkowski norm of each product vector
    normas = [minkowski_norm(v, p) for v in resultado]
    # Find the maximum norm
    maximo = max(normas)
    return maximo



##### Aquí se debe de ingresar el valor de n = #, luego el valor de m = # y por ultimo de la norma que se quiere hallar P = "1", "2" y "inf". 

In [3]:
n =5
m =10
p = 2 

max_norm = max_minkowski_norm(n, m, p)
print(max_norm)

15.748015748023622


### Si se quiere ver el paso a paso detallado de como funciona el algoritmo, en las proximas lineas se muestra explicitamente como funciona.

##### Función para crear una matriz aleatoria

In [4]:
def random_matrix(n, m):
    # Generate a random matrix of size n by m with integer numbers
    matrix = np.random.randint(low=0, high=10, size=(n, m))
    return matrix

##### Se generan los números aleatorios para alimentar la función de la matriz

In [5]:
n =  random.randint(2, 11)
m = random.randint(2, 11)

x = random_matrix(n,m)
print(x)
x.shape

[[1 7 4 6 0 6]
 [5 9 3 3 4 4]
 [5 9 9 2 0 4]
 [2 9 0 6 0 7]
 [8 9 4 3 0 5]
 [9 7 1 8 8 8]
 [1 7 4 9 5 4]
 [0 6 1 1 0 2]]


(8, 6)

##### Se crean los vectores Canonicos con tamño "n" y el número de vectores es "m" 

In [6]:
x = random_matrix(n, m)

vectores_canonicos = [] # Lista de vectores canónicos aleatorios

for i in range(m): # Generar m vectores canónicos
    e = np.zeros(n) # Vector canónico de longitud n
    e[i % n] = 1 # Establecer el valor de 1 en la posición correspondiente
    vectores_canonicos.append(e) # Agregar el vector canónico a la lista

for e in vectores_canonicos:
    print(e)

[1. 0. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0.]
[0. 0. 0. 0. 0. 1. 0. 0.]


In [7]:
vectores_canonicos[0].shape

(8,)

##### Se hace la multiplicación de la matriz aleatoria y los vectores canonicos 

In [8]:
resultado = [np.transpose(x) @ vectores_canonicos[i] for i in range(len(vectores_canonicos))]
print(resultado)

[array([3., 9., 6., 2., 9., 5.]), array([8., 7., 8., 0., 4., 9.]), array([8., 1., 6., 2., 9., 7.]), array([2., 2., 0., 1., 2., 1.]), array([6., 1., 8., 8., 9., 6.]), array([0., 1., 2., 8., 3., 6.])]


##### Se crea la función para generar normas vectoriales

In [9]:
def minkowski_norm(x, p):
    # Calculate the Minkowski norm of a vector x with order p
    if p == 1:
        norm = np.sum(np.abs(x))
    elif p == 2:
        norm = np.sqrt(np.sum(np.square(x)))
    elif p == float('inf'):
        norm = np.max(np.abs(x))
    return norm

##### Aquí se debe de escoger la norma que se desea implementar. (1,2,infinito)

In [10]:
# Normas P 
p = 1 
# p = 2
# P = "inf"

normas =[]
for v in resultado:
    norma = minkowski_norm(v,p)
    normas.append(norma)
    
print(normas)

[34.0, 36.0, 33.0, 8.0, 38.0, 20.0]


##### Se saca el maximo de las normas vectoriales 

In [11]:
maximo = max(normas)
print(maximo)  ## Esta es la norma inducida para la matriz generada

38.0
